name: Add new opened issue to project

on:
  issues:
    types: [opened]

jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          project-number: 2
          column-name: Backlog
